/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin: typeof import('./../../src/layouts/admin/index.vue')['default']
    AdminHistoryMenu: typeof import('./../../src/layouts/admin/historyMenu.vue')['default']
    AdminLeftMenu: typeof import('./../../src/layouts/admin/leftMenu.vue')['default']
    AdminNavbar: typeof import('./../../src/layouts/admin/navbar.vue')['default']
    Auth: typeof import('./../../src/layouts/auth/index.vue')['default']
    Error: typeof import('./../../src/layouts/error/index.vue')['default']
    Front: typeof import('./../../src/layouts/front/index.vue')['default']
    HdAnimateList: typeof import('./../../src/components/hd/animateList.vue')['default']
    HdBreadcrumb: typeof import('./../../src/components/hd/breadcrumb.vue')['default']
    HdError: typeof import('./../../src/components/hd/error.vue')['default']
    HdFormButton: typeof import('./../../src/components/hd/formButton.vue')['default']
    HdFormInput: typeof import('./../../src/components/hd/formInput.vue')['default']
    HdMarkdownEditor: typeof import('./../../src/components/hd/markdownEditor.vue')['default']
    HdMarkdownPreview: typeof import('./../../src/components/hd/markdownPreview.vue')['default']
    HdUploadSingleImage: typeof import('./../../src/components/hd/uploadSingleImage.vue')['default']
    HdUserAvatarMenu: typeof import('./../../src/components/hd/userAvatarMenu.vue')['default']
    HdVideoPlayer: typeof import('./../../src/components/hd/videoPlayer.vue')['default']
    HdWangEditor: typeof import('./../../src/components/hd/wangEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
