/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin: typeof import('./../../src/layouts/admin/index.vue')['default']
    AdminHistoryMenu: typeof import('./../../src/layouts/admin/historyMenu.vue')['default']
    AdminLeftMenu: typeof import('./../../src/layouts/admin/leftMenu.vue')['default']
    AdminNavbar: typeof import('./../../src/layouts/admin/navbar.vue')['default']
    Auth: typeof import('./../../src/layouts/auth/index.vue')['default']
    Detail: typeof import('./../../src/layouts/detail/index.vue')['default']
    DetailMemberNavbar: typeof import('./../../src/layouts/detail/memberNavbar.vue')['default']
    DetailUserBlock: typeof import('./../../src/layouts/detail/userBlock.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Error: typeof import('./../../src/layouts/error/index.vue')['default']
    Front: typeof import('./../../src/layouts/front/index.vue')['default']
    FrontFooter: typeof import('./../../src/layouts/front/footer.vue')['default']
    HdAnimateList: typeof import('./../../src/components/hd/animateList.vue')['default']
    HdBreadcrumb: typeof import('./../../src/components/hd/breadcrumb.vue')['default']
    HdCaptcha: typeof import('./../../src/components/hd/captcha.vue')['default']
    HdCard: typeof import('./../../src/components/hd/card.vue')['default']
    HdCodeSend: typeof import('./../../src/components/hd/codeSend.vue')['default']
    HdError: typeof import('./../../src/components/hd/error.vue')['default']
    HdFormButton: typeof import('./../../src/components/hd/formButton.vue')['default']
    HdFormInput: typeof import('./../../src/components/hd/formInput.vue')['default']
    HdFullScreen: typeof import('./../../src/components/hd/fullScreen.vue')['default']
    HdMarkdownEditor: typeof import('./../../src/components/hd/markdownEditor.vue')['default']
    HdMarkdownPreview: typeof import('./../../src/components/hd/markdownPreview.vue')['default']
    HdUploadSingleImage: typeof import('./../../src/components/hd/uploadSingleImage.vue')['default']
    HdUserAvatarMenu: typeof import('./../../src/components/hd/userAvatarMenu.vue')['default']
    HdVideoPlayer: typeof import('./../../src/components/hd/videoPlayer.vue')['default']
    HdWangEditor: typeof import('./../../src/components/hd/wangEditor.vue')['default']
    HdWechatLogin: typeof import('./../../src/components/hd/wechatLogin.vue')['default']
    IconInfo: typeof import('@icon-park/vue-next')['Info']
    IconPeople: typeof import('@icon-park/vue-next')['People']
    IconUpSquare: typeof import('@icon-park/vue-next')['UpSquare']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
