// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EditorMarkdown: typeof import('./../src/components/editor/markdown.vue')['default']
    EditorWangEditor: typeof import('./../src/components/editor/wangEditor.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    FormButtonComponent: typeof import('./../src/components/form/buttonComponent.vue')['default']
    FormError: typeof import('./../src/components/form/error.vue')['default']
    FormFieldList: typeof import('./../src/components/form/fieldList.vue')['default']
    FormInputComponent: typeof import('./../src/components/form/inputComponent.vue')['default']
    FormVeeValidateError: typeof import('./../src/components/form/veeValidateError.vue')['default']
    HdAnimateList: typeof import('./../src/components/hd/animateList.vue')['default']
    HdBreadcrumb: typeof import('./../src/components/hd/breadcrumb.vue')['default']
    HdCaptcha: typeof import('./../src/components/hd/captcha.vue')['default']
    HdFullscreen: typeof import('./../src/components/hd/fullscreen.vue')['default']
    HdNotification: typeof import('./../src/components/hd/notification.vue')['default']
    HdTab: typeof import('./../src/components/hd/tab.vue')['default']
    HdTableComponent: typeof import('./../src/components/hd/tableComponent.vue')['default']
    HdValidateCode: typeof import('./../src/components/hd/validateCode.vue')['default']
    ModuleSelectModule: typeof import('./../src/components/module/selectModule.vue')['default']
    SiteItem: typeof import('./../src/components/site/item.vue')['default']
    UploadSingleImage: typeof import('./../src/components/upload/singleImage.vue')['default']
    UserDrop: typeof import('./../src/components/user/drop.vue')['default']
    UserInfo: typeof import('./../src/components/user/info.vue')['default']
    UserSelectUser: typeof import('./../src/components/user/selectUser.vue')['default']
  }
}

export { }
