// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/animateList.vue')['default']
    Breadcrumb: typeof import('./../src/components/breadcrumb.vue')['default']
    HdButton: typeof import('./../src/components/hd/button.vue')['default']
    HdInput: typeof import('./../src/components/hd/input.vue')['default']
    HdLink: typeof import('./../src/components/hd/link.vue')['default']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    Notification: typeof import('./../src/components/notification.vue')['default']
    WangEditorEditor: typeof import('./../src/components/wangEditor/editor.vue')['default']
  }
}

export { }
