// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormButtonComponent: typeof import('./../../src/components/form/buttonComponent.vue')['default']
    FormInputComponent: typeof import('./../../src/components/form/inputComponent.vue')['default']
    HdAnimateList: typeof import('./../../src/components/hd/animateList.vue')['default']
    HdBreadcrumb: typeof import('./../../src/components/hd/breadcrumb.vue')['default']
    HdCode: typeof import('./../../src/components/hd/code.vue')['default']
    HdError: typeof import('./../../src/components/hd/error.vue')['default']
    HdFormRender: typeof import('./../../src/components/hd/formRender.vue')['default']
    HdFullscreen: typeof import('./../../src/components/hd/fullscreen.vue')['default']
    HdMarkdown: typeof import('./../../src/components/hd/markdown.vue')['default']
    HdMarkdownPreview: typeof import('./../../src/components/hd/markdownPreview.vue')['default']
    HdTab: typeof import('./../../src/components/hd/tab.vue')['default']
    HdTableRender: typeof import('./../../src/components/hd/tableRender.vue')['default']
    HdWangEditor: typeof import('./../../src/components/hd/wangEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadSingleImage: typeof import('./../../src/components/upload/singleImage.vue')['default']
  }
}
